### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Jme7** [Jme7/Jme7.github.io#10]
Ch1ck3n, could you help with the "logo" and other features you were talking about?
mention @ch1ck3n-byte 

I've added leanboard (you can get it at https://github.com/marketplace/leanboard/) so here is the board:
https://app.leanboard.io/board/16181a77-ea55-4099-be59-c1e5342992b9

**Comment by ch1ck3n-byte** [comment]
I added a favicon.ico you can change it but it HAS to be an .ico file AND the name has to be "favicon"

**Comment by Jme7** [comment]
Thanks! I was wondering where it is, but I've found it.

**Comment by Jme7** [comment]
How do you edit it?
mention @ch1ck3n-byte

**Comment by Jme7** [comment]
Well, I still want to know how it is edited, but I have an icon for now

**Comment by Jme7** [comment]
Thanks! Although I have made some new ones... But I wouldn't have even known about favicons without that, so thank you!

**Comment by Jme7** [comment]
Ok, this is done.
